apiVersion: v1
kind: Service
metadata:
  name: filmrentals-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: filmrentals
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: filmrentals
  template:
    metadata:
      labels:
        app: filmrentals
    spec:
      nodeSelector:
        hardware: powerproc
      containers:
      - name: filmrentals-ctr
        image:  jpwsregistry.azurecr.io/filmrentals:v1
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef: 
              name: mysqlserver-mysqlappdbserver
              key: fullyQualifiedUsername
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mysqlserver-mysqlappdbserver
              key: password
        - name: MYSQL_SERVICE_HOST
          valueFrom: 
            secretKeyRef: 
              name: mysqlserver-mysqlappdbserver
              key: fullyQualifiedServerName
        - name: MYSQL_SERVICE_PORT
          value: '3306'

