apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLServer
metadata:
  name: mysqlappdbserver
spec:  
  location: eastus2
  resourceGroup: mysqlcluster
  serverVersion: "5.7"
  sslEnforcement: Enabled
  createMode: Default # Possible values include: Default, Replica, PointInTimeRestore (not implemented), GeoRestore (not implemented)
  sku:
    name: GP_Gen5_4 # tier + family + cores eg. - B_Gen4_1, GP_Gen5_4
    tier: GeneralPurpose # possible values - 'Basic', 'GeneralPurpose', 'MemoryOptimized'
    family: Gen5 
    size: "51200"
    capacity: 4
---
apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLFirewallRule
metadata:
  name: mysqlfirewallrule-azureservices
spec:
  resourceGroup: mysqlcluster
  server: mysqlappdbserver
  startIpAddress: 0.0.0.0
  endIpAddress: 0.0.0.0
---
apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLFirewallRule
metadata:
  name: mysqlfirewallrule-clientmachine
spec:
  resourceGroup: mysqlcluster
  server: mysqlappdbserver
  startIpAddress: 90.248.78.241
  endIpAddress: 90.248.78.241
---
apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLDatabase
metadata:
  name: filmrental
spec:
  resourceGroup: mysqlcluster
  server: mysqlappdbserver
