apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filmrentals
  template:
    metadata:
      labels:
        app: filmrentals
    spec:
      nodeSelector:
        hardware: powerproc
      containers:
      - name: filmrentals-ctr
        image:  jpwsregistry.azurecr.io/filmrentals:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: filmrentals-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: filmrentals
